### ISSUE TITLE
Unreleased version on plugins.jetbrains.com

### ISSUE THREAD

**Issue by YoannMa** [darekkay/what-the-commit#4]
Hey there, huge fan of the extension 🙏

Could you do a release on [plugins.jetbrains.com](https://plugins.jetbrains.com/plugin/7536-what-the-commit) as the current extension is not working anymore without #3

This tool is the best way to get the most of the Git experience, and I would be saddened if peoples couldn't easily use it 😢

**Comment by darekkay** [comment]
Done!

https://plugins.jetbrains.com/plugin/7536-what-the-commit

**Comment by YoannMa** [comment]
Thank you very much, you are a savior!
